import "@radix-ui/themes/styles.css";
import "../theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import { Container, Theme } from "@radix-ui/themes";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";
import SocketProvider from "./socket/socketProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={inter.variable}>
        <AuthProvider>
          <QueryClientProvider>
            <SocketProvider>
              <Theme
                accentColor="amber"
                grayColor="gray"
              >
                <NavBar />
                <main className="p-5">
                  <Container>{children}</Container>
                </main>
              </Theme>
            </SocketProvider>
          </QueryClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
